[book]
authors = ["ritchie46"]
language = "zh-CN"
src = "src"
title = "Polars - 用户指南"

[output.html]
default-theme = "Ayu"
mathjax-support = true

[output.html.fold]
enable = true
level = 1

# custom preprocessor to insert the reference guide links
[preprocessor.replace]
command = "python preprocessor/replace.py"
